#!/bin/bash
set -euo pipefail

user=u289320-sub1
server=u289320-sub1.your-storagebox.de
port=23
sshkeypath=$HOME/.ssh/id_rsa_jellyfin

# transfer Music
rsync -uvrL --progress --bwlimit=4M -e "ssh -i $sshkeypath -p $port" /home/marc/Musik/ ${user}@${server}:Musik/

# transfer Shows
rsync -uvr --progress --bwlimit=4M -e "ssh -i $sshkeypath -p $port" /mnt/storage/MediaLibrary/Shows/ ${user}@${server}:Shows/

# transfer Movies
rsync -uvr --progress --bwlimit=4M -e "ssh -i $sshkeypath -p $port" /mnt/storage/MediaLibrary/Movies/ ${user}@${server}:Movies/
