#!/bin/bash
set -euo pipefail

user=exu
server=172.18.50.100
port=22
sshkeypath=$HOME/.ssh/id_ed25519
# don't transfer to the storage box directly, leads to mangled file names
# see: https://serverfault.com/a/765951

# transfer to kavita
# books
echo Kavita books upload
rsync -urtzv --bwlimit=4M -e "ssh -i $sshkeypath -p $port" /home/marc/Nextcloud/Books/Unterhaltung/ ${user}@${server}:/mnt/books/kavita/books/
# manga
echo Kavita manga upload
rsync -urtzv --bwlimit=4M -e "ssh -i $sshkeypath -p $port" /home/marc/Nextcloud/Books/Manga/ ${user}@${server}:/mnt/books/kavita/manga/
# Tech
echo Kavita tech upload
rsync -urtzv --bwlimit=4M -e "ssh -i $sshkeypath -p $port" /home/marc/Nextcloud/Books/Tech/ ${user}@${server}:/mnt/books/kavita/tech/
# other
echo Kavita other upload
rsync -urtzv --bwlimit=4M -e "ssh -i $sshkeypath -p $port" /home/marc/Nextcloud/Books/other/ ${user}@${server}:/mnt/books/kavita/other/

# transfer to komga
# TODO

# transfer to kavita-nightly
# books
echo Kavita Nightly books upload
rsync -urtzv --bwlimit=4M -e "ssh -i $sshkeypath -p $port" /home/marc/Nextcloud/Books/Unterhaltung/ ${user}@${server}:/mnt/books/kavita-nightly/books/
# manga
echo Kavita Nightly manga upload
rsync -urtzv --bwlimit=4M -e "ssh -i $sshkeypath -p $port" /home/marc/Nextcloud/Books/Manga/ ${user}@${server}:/mnt/books/kavita-nightly/manga/
# Tech
echo Kavita Nightly tech upload
rsync -urtzv --bwlimit=4M -e "ssh -i $sshkeypath -p $port" /home/marc/Nextcloud/Books/Tech/ ${user}@${server}:/mnt/books/kavita-nightly/tech/
# other
echo Kavita Nightly other upload
rsync -urtzv --bwlimit=4M -e "ssh -i $sshkeypath -p $port" /home/marc/Nextcloud/Books/other/ ${user}@${server}:/mnt/books/kavita-nightly/other/

# download from kavita
# books
#echo Downloading books
#rsync -ur --progress --bwlimit=4M -e "ssh -i $sshkeypath -p $port" ${user}@${server}:/mnt/books/kavita/books/ /home/marc/Nextcloud/Books/Unterhaltung/
# manga
echo Kavita manga download
rsync -urtzv --bwlimit=4M -e "ssh -i $sshkeypath -p $port" ${user}@${server}:/mnt/books/kavita/manga/ /home/marc/Nextcloud/Books/Manga/
# Tech
#echo Downloading tech
#rsync -ur --progress --bwlimit=4M -e "ssh -i $sshkeypath -p $port" ${user}@${server}:/mnt/books/kavita/tech/ /home/marc/Nextcloud/Books/Tech/
# other
#echo Downloading other
#rsync -ur --progress --bwlimit=4M -e "ssh -i $sshkeypath -p $port" ${user}@${server}:/mnt/books/kavita/other/ /home/marc/Nextcloud/Books/other/
