#!/usr/bin/env bash
set -euo pipefail

# INPUT
# To upload new files, symlink/copy them to /mnt/storage/MediaLibrary/_tdarr-input/

# OUTPUT
# Output from tdarr will be downloaded to /mnt/storage/MediaLibrary/_tdarr-output/

echo "uploading new Content"
rsync -uvrL --progress --bwlimit=2M /mnt/storage/MediaLibrary/_tdarr-input/ exu@172.18.50.109:/mnt/tdarrshare/tdarr-share/media/input/

echo "downloading conversions"
rsync -uvr --progress --bwlimit=2M exu@172.18.50.109:/mnt/tdarrshare/tdarr-share/media/output/ /mnt/storage/MediaLibrary/_tdarr-output/
