---
- name: Async (check) | Check on async jobs
  async_status:
    jid: "{{ item.ansible_job_id }}"
  loop:
    - "{{ async_doom_emacs }}"
    - "{{ async_fish_completions }}"
  register: job_result
  until: job_result.finished
  retries: 60
  delay: 10

- name: Async (cleanup) | Cleanup async jobs
  async_status:
    jid: "{{ item.ansible_job_id }}"
    mode: cleanup
  loop:
    - "{{ async_doom_emacs }}"
    - "{{ async_fish_completions }}"
# - name: Async (check) | Check on Doom Emacs async job
#   async_status:
#     jid: "{{ async_doom_emacs.ansible_job_id }}"
#   register: job_result
#   until: job_result.finished
#   retries: 60
#   delay: 10

# - name: Async (cleanup) | Cleanup Doom Emacs async job
#   async_status:
#     jid: "{{ async_doom_emacs.ansible_job_id }}"
#     mode: cleanup

# - name: Async (check) | Check on Fish async job
#   async_status:
#     jid: "{{ async_fish_completions.ansible_job_id }}"
#   register: job_result
#   until: job_result.finished
#   retries: 60
#   delay: 10

# - name: Async (cleanup) | Cleanup Fish async job
#   async_status:
#     jid: "{{ async_fish_completions.ansible_job_id }}"
#     mode: cleanup
