---
- name: Fish | Update completions
  ansible.builtin.shell:
    cmd: "fish_update_completions"
    executable: "/usr/bin/fish"
  changed_when: true
  tags: config

- name: Fish | Set fish for user
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    shell: "/usr/bin/fish"
  become: true
  tags: config

- name: Fish | Set fish for root
  ansible.builtin.user:
    name: "root"
    shell: "/usr/bin/fish"
  become: true
  tags: config
