---
- name: Gather the package facts
  ansible.builtin.package_facts:
  tags: always

# Preparation tasks: backup, removals
- name: Import Tasks from preparation.yml
  ansible.builtin.import_tasks:
    file: preparation.yml
  tags: config

# Copy new files
- name: Import Tasks from copy_files.yml
  ansible.builtin.import_tasks:
    file: copy_files.yml
  tags: config

- name: Symlink xdg environment variables
  ansible.builtin.file:
    src: "~/.config/user-dirs.dirs"
    dest: "~/.config/environment.d/user-dirs.dirs.conf"
    state: "link"
  tags: config

- name: Create flatpak overrides
  ansible.builtin.command: "flatpak override --user {{ item }}"
  changed_when: true
  loop:
    - "--filesystem=~/.themes:ro" # correct gtk/qt theme
    - "--filesystem=xdg-config/kcminputrc:ro" # correct cursor theme https://github.com/flatpak/flatpak/issues/709#issuecomment-2133355601
    - "--socket=wayland"

# bash cat
- name: Import Tasks from bash_cat.yml
  ansible.builtin.import_tasks:
    file: bash_cat.yml
  tags: config

# fish
- name: Import Tasks from fish.yml
  ansible.builtin.import_tasks:
    file: fish.yml
  tags: config

# systemd
- name: Import Tasks from systemd.yml
  ansible.builtin.import_tasks:
    file: systemd.yml
  tags: config

- name: Create groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop:
    - video # backlight
    - render # GPU passing
    - wireguard # wireguard
  become: true
  tags: config

- name: Add user to groups
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups:
      - video # backlight
      - render # GPU passing
      - wireguard # wireguard
    append: true
  become: true
  tags: config

- name: Symlink systemd-resolved config file for /etc/resolv.conf
  ansible.builtin.file:
    src: "/run/systemd/resolve/stub-resolv.conf"
    dest: "/etc/resolv.conf"
    state: link
    force: true
  become: true
  tags: config

- name: Set sudoers.d permissions
  ansible.builtin.file:
    path: /etc/sudoers.d
    mode: "600"
    owner: root
    group: root
    recurse: true
  become: true
  tags: config

- name: Make scripts executable
  ansible.builtin.file:
    path: "{{ item }}"
    mode: u+x,g+x,o+x
    recurse: true
  loop:
    - "~/scripts"
  tags: config

- name: Import Tasks from plasma.yml
  ansible.builtin.import_tasks:
    file: plasma.yml
  tags: config
