---
# Plasma shell running
- name: Plasma | Check if plasma shell is running
  community.general.pids:
    name: plasmashell
  register: config_plasma_process
  tags: config

# Temporary directory
- name: Plasma | Create temporary download directory
  ansible.builtin.tempfile:
    state: directory
    prefix: "ansible.config."
  register: tempdir
  tags: config

# Temporary directory
- name: Plasma | Create temporary download structure
  ansible.builtin.file:
    path: "{{ tempdir.path }}/{{ item }}"
    state: "directory"
    mode: "0755"
  loop:
    - "icons"
    - "plasma/desktoptheme"
    - "themes"
  tags: config

# Wallpaper
- name: Plasma | Check if wallpaper exists for user
  ansible.builtin.stat:
    path: "{{ background_image }}"
  register: wallpaper_user
  tags: config

# Wallpaper
- name: Plasma | Copy wallpaper to global location (root)
  ansible.builtin.copy:
    src: "{{ background_image }}"
    dest: "/etc/wallpaper.jpg"
    mode: "0644"
    remote_src: true
  become: true
  tags: config
  when: wallpaper_user.stat.exists

# Theme
- name: Plasma | Get desktop theme
  ansible.builtin.unarchive:
    src: https://github.com/EliverLara/Sweet-kde/archive/refs/heads/master.zip
    dest: "{{ tempdir.path }}/plasma/desktoptheme/"
    remote_src: true
  tags: config

# Theme
- name: Plasma | Copy desktop theme (root)
  ansible.builtin.copy:
    src: "{{ tempdir.path }}/plasma/desktoptheme/Sweet-kde-master/"
    dest: "/usr/share/plasma/desktoptheme/Sweet/"
    remote_src: true
  become: true
  tags: config

# Theme
- name: Plasma | Get theme
  ansible.builtin.unarchive:
    src: https://github.com/EliverLara/Sweet/archive/refs/heads/nova.zip
    dest: "{{ tempdir.path }}/themes/"
    remote_src: true
  tags: config

# Theme
# mainly for Flatpak, which can't use the theme any other way
- name: Plasma | Copy theme
  ansible.builtin.copy:
    src: "{{ tempdir.path }}/themes/Sweet-nova"
    dest: "~/.local/share/themes/"
    remote_src: true
    mode: "0755"
  tags: config

# Theme
- name: Plasma | Copy theme (root)
  ansible.builtin.copy:
    src: "{{ tempdir.path }}/themes/Sweet-nova"
    dest: "/usr/share/themes/"
    remote_src: true
    mode: "0755"
  become: true
  tags: config

# Theme
- name: Plasma | Get Kitty cursor theme
  ansible.builtin.unarchive:
    src: "files/Kitty.tar.gz"
    dest: "{{ tempdir.path }}/icons/"
  tags: config

# Icon
- name: Plasma | Get icons
  ansible.builtin.unarchive:
    src: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/archive/refs/heads/master.zip
    dest: "{{ tempdir.path }}/icons/"
    remote_src: true
  tags: config

# Icon
- name: Plasma | Copy icons (root)
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/share/icons/"
    remote_src: true
    mode: "0755"
  loop:
    - "{{ tempdir.path }}/icons/Kitty"
    - "{{ tempdir.path }}/icons/papirus-icon-theme-master/Papirus"
    - "{{ tempdir.path }}/icons/papirus-icon-theme-master/Papirus-Dark"
    - "{{ tempdir.path }}/icons/papirus-icon-theme-master/Papirus-Light"
  become: true
  tags: config

# Theme
- name: Plasma | Copy files (root)
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: true
    mode: "0644"
  loop:
    - src: "/usr/share/themes/Sweet-nova/kde/colorschemes/Sweet.colors"
      dest: "/usr/share/color-schemes/Sweet.colors"
  become: true
  tags: config

# Theme
- name: Plasma | Copy folders (root)
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: true
    mode: "0755"
  loop:
    - src: "/usr/share/themes/Sweet-nova/kde/look-and-feel/"
      dest: "/usr/share/plasma/look-and-feel/Sweet/"
  become: true
  tags: config

# Set cursor
- name: Plasma | Set cursor theme
  ansible.builtin.command: "plasma-apply-cursortheme Kitty"
  when: config_plasma_process['pids'] | length > 0
  tags: config
  changed_when: true

# Set colorscheme
- name: Plasma | Set colorscheme
  ansible.builtin.command: "plasma-apply-colorscheme Sweet"
  when: config_plasma_process['pids'] | length > 0
  tags: config
  changed_when: true

# Set desktop theme
- name: Plasma | Set desktop theme
  ansible.builtin.command: "plasma-apply-desktoptheme Sweet"
  when: config_plasma_process['pids'] | length > 0
  tags: config
  changed_when: true

# Wallpaper
- name: Plasma | Check if wallpaper exists
  ansible.builtin.stat:
    path: "/etc/wallpaper.jpg"
  register: wallpaper
  tags: config

# Wallpaper
- name: Plasma | Apply wallpaper everywhere
  when: wallpaper.stat.exists
  tags: config
  block:
    # - name: Plasma | Remove previously set wallpapers
    #   ansible.builtin.shell: |
    #     kwriteconfig6 --file ~/.config/plasma-org.kde.plasma.desktop-appletsrc --group Containments --group 1 --group Wallpaper --group org.kde.image --group General --key Image --delete
    #     kwriteconfig6 --file ~/.config/plasma-org.kde.plasma.desktop-appletsrc --group Containments --group 1 --group Wallpaper --group org.kde.image --group General --key FillMode --delete
    #     kwriteconfig6 --file ~/.config/plasma-org.kde.plasma.desktop-appletsrc --group Containments --group 2 --group Wallpaper --group org.kde.image --group General --key Image --delete
    #     kwriteconfig6 --file ~/.config/plasma-org.kde.plasma.desktop-appletsrc --group Containments --group 1 --group Wallpaper --group org.kde.image --group General --key FillMode --delete
    #   tags: config

    - name: Plasma | Set desktop wallpaper
      ansible.builtin.command: 'plasma-apply-wallpaperimage "/etc/wallpaper.jpg"'
      changed_when: true
      when: config_plasma_process['pids'] | length > 0

    # - name: Plasma | Set desktop wallpaper
    #   ansible.builtin.shell: |
    #     qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript "
    #                 desktops().forEach((d) => {
    #                     d.currentConfigGroup = [
    #                         'Wallpaper',
    #                         'org.kde.image',
    #                         'General',
    #                     ]
    #                     d.writeConfig('Image', '{{ background_image }}')
    #                     d.reloadConfig()
    #                 })
    #             "
    #   tags: config

    - name: Plasma | Set Lockscreen wallpaper
      ansible.builtin.shell: |
        kwriteconfig6 --file ~/.config/kscreenlockerrc --group Greeter --group Wallpaper --group org.kde.image --group General --key Image '/etc/wallpaper.jpg'
        kwriteconfig6 --file ~/.config/kscreenlockerrc --group Greeter --group Wallpaper --group org.kde.image --group General --key PreviewImage '/etc/wallpaper.jpg'
      changed_when: true

# Plasma login
- name: Plasma | Create plasmalogin directory structure
  ansible.builtin.file:
    path: "/var/lib/plasmalogin/{{ item }}"
    state: "directory"
    mode: "0755"
    owner: plasmalogin
    group: plasmalogin
  loop:
    - ".config"
    - ".config/fontconfig"
    - ".config/kdedefaults"
    - "wallpapers"
  become: true
  tags: config

# Plasma login (check)
- name: Check if KDE files exist
  ansible.builtin.stat:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/kwinoutputconfig.json"
  register: kde_files
  tags: config

# Plasma login
- name: Copy config for Plasma login (root)
  ansible.builtin.copy:
    src: "{{ lookup('ansible.builtin.env', 'HOME') }}/{{ item }}"
    dest: "/var/lib/plasmalogin/.config/"
    mode: "0644"
    owner: plasmalogin
    group: plasmalogin
    remote_src: true
  loop:
    - ".config/Trolltech.conf"
    - ".config/fontconfig/fonts.conf"
    - ".config/gtkrc"
    - ".config/gtkrc-2.0"
    - ".config/kcminputrc"
    - ".config/kdedefaults/kcminputrc"
    - ".config/kdedefaults/kdeglobals"
    - ".config/kdedefaults/ksplashrc"
    - ".config/kdedefaults/kwinrc"
    - ".config/kdedefaults/package"
    - ".config/kdedefaults/plasmarc"
    - ".config/kdeglobals"
    - ".config/kglobalshortcutsrc"
    - ".config/kwinoutputconfig.json"
    - ".config/kwinrc"
    - ".config/kwinrulesrc"
    - ".config/kxkbrc"
    - ".config/plasma-localerc"
    - ".config/plasmarc"
  when: kde_files.stat.exists
  become: true
  tags: config

# Plasma login
- name: Copy wallpaper for Plasma login (root)
  ansible.builtin.copy:
    src: "{{ background_image }}"
    dest: "/var/lib/plasmalogin/wallpapers/wallpaper.jpg"
    mode: "0644"
    owner: plasmalogin
    group: plasmalogin
    remote_src: true
  when: wallpaper.stat.exists
  become: true
  tags: config

## Restart to apply changes
# TODO: alternative commands
# kill plasmashell
# kquitapp6 plasmashell
# kstart plasmashell
#
# NOTE restarting plasmashell removes the just set background images
# - name: Plasma | Restart plasmashell
#   ansible.builtin.command: kquitapp6 plasmashell
#   changed_when: true
#   tags: config

# Plasma restart
- name: Plasma | Restart krunner
  ansible.builtin.command: kquitapp6 krunner
  changed_when: true
  ignore_errors: true
  tags: config
