---
# additional_pacman_packages:
#   - wireguard-tools
#additional_aur_packages:
#  - netclient-bin

ssh_key_git: "{{ ansible_facts['user_dir'] }}/.ssh/id_ed25519_git"

background_image: "{{ ansible_facts['user_dir'] }}/Bilder/On_the_Way_to_SafespaceStation1_Sylvia.Ritter.jpg"
