---
# path to ssh key for git servers
ssh_key_git: "{{ ansible_facts['user_dir'] }}/.ssh/id_ed25519_git"
# desktop background image
background_image: "{{ ansible_facts['user_dir'] }}/Bilder/Art/Patreon/Sylvia Ritter/On_the_Way_to_SafespaceStation1_Sylvia.Ritter.jpg"
